pipeline:
  publish:
    image: plugins/docker
    repo: mrpolo17/drone-docker
    tages: [ latest ]
    dockerfile: Dockerfile
    secrets: 
      - source: docker_user
        target: docker_username
      - source: docker_pwd
        target: docker_password